name: Publish to pub.dev

on:
  push:    
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write 
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter dependencies
        run: flutter pub get
      - uses: dart-lang/setup-dart@v1
      - name: Publish -dry run
        run: dart pub publish --dry-run
      - name: Publish
        run: dart pub publish --force
